import { readFileSync, existsSync } from 'fs';
import { DialectIdentityTest, TranspilationTest } from '../types/index.js';

/**
 * Load extracted dialect tests from JSON files.
 * These files are generated by the Python extract-tests.py script.
 */
export interface ExtractedDialectTests {
  dialect: string;
  identity: DialectIdentityTest[];
  transpilation: TranspilationTest[];
}

export function loadDialectTests(jsonPath: string): ExtractedDialectTests | null {
  if (!existsSync(jsonPath)) {
    return null;
  }

  const content = readFileSync(jsonPath, 'utf-8');
  const data = JSON.parse(content);

  const identity: DialectIdentityTest[] = (data.identity || []).map((test: any, i: number) => ({
    id: `${data.dialect}_identity_${i + 1}`,
    dialect: data.dialect,
    sql: test.sql,
    expectedSql: test.expected || null,
    category: 'dialect_identity' as const,
  }));

  const transpilation: TranspilationTest[] = (data.transpilation || []).map((test: any, i: number) => ({
    id: `${data.dialect}_transpile_${i + 1}`,
    dialect: data.dialect,
    sql: test.sql,
    read: test.read || {},
    write: test.write || {},
    category: 'transpilation' as const,
  }));

  return {
    dialect: data.dialect,
    identity,
    transpilation,
  };
}

/**
 * Load all dialect tests from the fixtures directory.
 */
export function loadAllDialectTests(fixturesDir: string): ExtractedDialectTests[] {
  // All 32 dialects from fixtures/extracted/dialects/*.json
  const dialects = [
    'athena', 'bigquery', 'clickhouse', 'databricks', 'doris', 'dremio',
    'drill', 'druid', 'duckdb', 'dune', 'exasol', 'fabric', 'hive',
    'materialize', 'mysql', 'oracle', 'pipe_syntax', 'postgres', 'presto',
    'prql', 'redshift', 'risingwave', 'singlestore', 'snowflake', 'solr',
    'spark', 'sqlite', 'starrocks', 'tableau', 'teradata', 'trino', 'tsql'
  ];

  const results: ExtractedDialectTests[] = [];

  for (const dialect of dialects) {
    const path = `${fixturesDir}/${dialect}.json`;
    const tests = loadDialectTests(path);
    if (tests) {
      results.push(tests);
    }
  }

  return results;
}

/**
 * Directory containing extracted dialect test JSON files
 */
export const DIALECTS_FIXTURE_DIR = 'fixtures/extracted/dialects';
