// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * AnalyzeHistogram
 */
export type AnalyzeHistogram = { this: Expression, expressions: Array<Expression>, expression: Expression | null, update_options: Expression | null, };
