// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * Expression annotated with trailing comments (for round-trip preservation)
 */
export type Annotated = { this: Expression, trailing_comments: Array<string>, };
