// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * ApproxTopSum
 */
export type ApproxTopSum = { this: Expression, expression: Expression, count: Expression | null, };
