// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * APPROX_PERCENTILE function
 */
export type ApproxPercentileFunc = { this: Expression, percentile: Expression, accuracy: Expression | null, filter: Expression | null, };
