// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * CheckXml
 */
export type CheckXml = { this: Expression, disable_auto_convert: Expression | null, };
