// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * ClusteredByProperty
 */
export type ClusteredByProperty = { expressions: Array<Expression>, sorted_by: Expression | null, buckets: Expression | null, };
