// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CommentColumnConstraint - Column comment marker
 */
export type CommentColumnConstraint = null;
