// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * Commit
 */
export type Commit = { chain: Expression | null, this: Expression | null, durability: Expression | null, };
