// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * ComputedColumnConstraint
 */
export type ComputedColumnConstraint = { this: Expression, persisted: Expression | null, not_null: Expression | null, data_type: Expression | null, };
