// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * ConditionalInsert
 */
export type ConditionalInsert = { this: Expression, expression: Expression | null, else_: Expression | null, };
