// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * Corr
 */
export type Corr = { this: Expression, expression: Expression, null_on_zero_variance: Expression | null, };
