// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * DateBin
 */
export type DateBin = { this: Expression, expression: Expression, unit: string | null, zone: Expression | null, origin: Expression | null, };
