// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";
import type { TableRef } from "./TableRef";

/**
 * DROP TRIGGER statement
 */
export type DropTrigger = { name: Identifier, table: TableRef | null, if_exists: boolean, cascade: boolean, };
