// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * ForeignKey
 */
export type ForeignKey = { expressions: Array<Expression>, reference: Expression | null, delete: Expression | null, update: Expression | null, options: Array<Expression>, };
