// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * Format override for a column in Teradata
 */
export type FormatPhrase = { this: Expression, format: string, };
