// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * FromTimeZone
 */
export type FromTimeZone = { this: Expression, zone: Expression | null, };
