// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * GroupingSets
 */
export type GroupingSets = { expressions: Array<Expression>, };
