// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * Into
 */
export type IntoClause = { this: Expression | null, temporary: boolean, unlogged: Expression | null, bulk_collect: Expression | null, expressions: Array<Expression>, };
