// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * IsolatedLoadingProperty
 */
export type IsolatedLoadingProperty = { no: Expression | null, concurrent: Expression | null, target: Expression | null, };
