// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * JSONPathSlice
 */
export type JSONPathSlice = { start: Expression | null, end: Expression | null, step: Expression | null, };
