// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * JSONColumnDef
 */
export type JSONColumnDef = { this: Expression | null, kind: string | null, path: Expression | null, nested_schema: Expression | null, ordinality: Expression | null, };
