// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * JSONValue
 */
export type JSONValue = { this: Expression, path: Expression | null, returning: Expression | null, on_condition: Expression | null, };
