// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * JSONObjectAgg
 */
export type JSONObjectAgg = { expressions: Array<Expression>, null_handling: Expression | null, unique_keys: Expression | null, return_type: Expression | null, encoding: Expression | null, };
