// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JSONPathRoot - Represents $ in JSON path expressions
 */
export type JSONPathRoot = null;
