// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * MD5Digest
 */
export type MD5Digest = { this: Expression, expressions: Array<Expression>, };
