// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * MergeBlockRatioProperty
 */
export type MergeBlockRatioProperty = { this: Expression | null, no: Expression | null, default: Expression | null, percent: Expression | null, };
