// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * NAMED_STRUCT function
 */
export type NamedStructFunc = { pairs: Array<[Expression, Expression]>, };
