// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * Normalize
 */
export type Normalize = { this: Expression, form: Expression | null, is_casefold: Expression | null, };
