// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * ParseUrl
 */
export type ParseUrl = { this: Expression, part_to_extract: Expression | null, key: Expression | null, permissive: Expression | null, };
