// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * PartitionByRangeProperty
 */
export type PartitionByRangeProperty = { partition_expressions: Expression | null, create_expressions: Expression | null, };
