// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * PathColumnConstraint - PATH 'xpath' for XMLTABLE/JSON_TABLE columns
 */
export type PathColumnConstraint = { this: Expression, };
