// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * Oracle PRIOR expression - references parent row's value in CONNECT BY
 */
export type Prior = { this: Expression, };
