// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * QueryOption
 */
export type QueryOption = { this: Expression, expression: Expression | null, };
