// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * QueryBand
 */
export type QueryBand = { this: Expression, scope: Expression | null, update: Expression | null, };
