// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * Randstr
 */
export type Randstr = { this: Expression, generator: Expression | null, };
