// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * Reference
 */
export type Reference = { this: Expression, expressions: Array<Expression>, options: Array<Expression>, };
