// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * RegexpExtractAll
 */
export type RegexpExtractAll = { this: Expression, expression: Expression, group: Expression | null, parameters: Expression | null, position: Expression | null, occurrence: Expression | null, };
