// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * RegrIntercept
 */
export type RegrIntercept = { this: Expression, expression: Expression, };
