// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * RegrR2
 */
export type RegrR2 = { this: Expression, expression: Expression, };
