// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * REPEAT function
 */
export type RepeatFunc = { this: Expression, times: Expression, };
