// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * REPLACE function
 */
export type ReplaceFunc = { this: Expression, old: Expression, new: Expression, };
