// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * SemanticView
 */
export type SemanticView = { this: Expression, metrics: Expression | null, dimensions: Expression | null, facts: Expression | null, where_: Expression | null, };
