// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * StDistance
 */
export type StDistance = { this: Expression, expression: Expression, use_spheroid: Expression | null, };
