// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * StringToArray
 */
export type StringToArray = { this: Expression, expression: Expression | null, null: Expression | null, };
