// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * TsOrDsDiff
 */
export type TsOrDsDiff = { this: Expression, expression: Expression, unit: string | null, };
