// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * Uniform
 */
export type Uniform = { this: Expression, expression: Expression, gen: Expression | null, seed: Expression | null, };
