// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * UniqueColumnConstraint
 */
export type UniqueColumnConstraint = { this: Expression | null, index_type: Expression | null, on_conflict: Expression | null, nulls: Expression | null, options: Array<Expression>, };
