// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * XMLGet
 */
export type XMLGet = { this: Expression, expression: Expression, instance: Expression | null, };
