// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * Xor
 */
export type Xor = { this: Expression | null, expression: Expression | null, expressions: Array<Expression>, };
