// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

/**
 * Zipf
 */
export type Zipf = { this: Expression, elementcount: Expression | null, gen: Expression | null, };
